### ISSUE TITLE
[1.19.2] Datapack not affecting gameplay

### ISSUE THREAD

**Issue by BigMartin58** [Nuparu00/TinyInv#15]
I set up my datapack and json to be exactly as the wiki instructs to make sure I followed everything correctly and nothing is happening. I have triple checked everything to make sure, but alas. I should mention I am using [Paxi](https://www.curseforge.com/minecraft/mc-mods/paxi) but it is functioning properly.

My file structure is "\data\tinyinv\default_attributes" and [this](https://mclo.gs/ceTeGmr) is my json:

**Comment by Nuparu00** [comment]
Hi.
Unfortunately, datapack support is present only in the 1.20.1 version.

**Comment by BigMartin58** [comment]
Will it ever come to 1.19.2? Most modpacks are still on that version and it'd be a real shame not to be able to include TinyInv in mine.

**Comment by BigMartin58** [comment]
I am trying to make a custom mod that utilizes this but I'm not seeing the listed attributes. I can assume that 1.19.2 has absolutely no real-time manipulation of inventory slots?

**Comment by Nuparu00** [comment]
There are no attributes in versions before 1.20.1. As the wiki stays - it is exclusively for the 1.20.1 version, most of the things written in there do not apply to the older versions.

Realistically, it should be fairly straightforward to backport the 1.20.1 version to 1.19.2 or even earlier.

**Comment by BigMartin58** [comment]
Sadge. I'm not capable of doing a full backport, I was just gonna make a mod that uses my own datapack to apply the attributes, but alas. Thank you anyway.

**Comment by Nuparu00** [comment]
I am not saying I won't backport it, I just don't have the time anytime soon. **If** everything goes right, I might have time to do modding in June at the earliest. If things go bad, well no idea what will happen.
