### ISSUE TITLE
Request open source 1.12.2 —— 请求开源1.12.2

### ISSUE THREAD

**Issue by Yi-Jian-Zai-Tian-Ya** [Nuparu00/TinyInv#17]
Please author open source version 1.12.2, this is really helpful to me, trouble the author**!!!**
请作者对1.12.2版本开源，这对我的帮助真的很大，麻烦作者了**！！！**

**Comment by Nuparu00** [comment]
I created a branch for the most recent 1.12.2 source I could find:
https://github.com/Nuparu00/TinyInv/tree/1.12.2

But as the readme file mentions, there are no guarantees whether it truly is the most recent 1.12.2 version, or something in between two versions, for example.

**Comment by Yi-Jian-Zai-Tian-Ya** [comment]
Thank you very much to the author for the source code, thank you for responding to my request so quickly, and thank you very much for creating such an educational value Mod for Minecraft.
非常感谢作者的源码，感谢你能这么高效地回复我的请求，也非常感谢你为《我的世界》创造了这么一款有教学意义的Mod。
